services:
  ecl:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      - "traefik.http.routers.ecl.rule=Host(`eclreact.almutasim.site`)"
      - "traefik.http.routers.ecl.entrypoints=web"
      - "traefik.http.services.ecl.loadbalancer.server.port=80"

networks:
  coolify:
    external: true
